### ISSUE TITLE
Would be awesome to easily scale the FlipDown

### ISSUE THREAD

**Issue by chuckbergeron** [PButcher/flipdown#5]
Awesome work here. This is the best looking and most performant JS Flip-style clock I've found. I'm integrating it into a site and I found that to handle small mobile devices I would need a custom @media breakpoint with a bunch of custom CSS to scale things down.

It'd be a great feature to have a way to scale it dynamically using maybe a percentage value as an option passed into the constructor: `new FlipDown()`

Here's what I ended up doing:

```css
@media (max-width: 576px) {
  .flipdown .rotor {
    font-size: 2.5rem;
  }

  .flipdown .rotor,
  .flipdown .rotor-leaf,
  .flipdown .rotor-leaf-front,
  .flipdown .rotor-leaf-rear,
  .flipdown .rotor-top,
  .flipdown .rotor-bottom,
  .flipdown .rotor:after {
    width: 30px;
  }

  .flipdown .rotor-group:nth-child(n+2):nth-child(-n+3):before,
  .flipdown .rotor-group:nth-child(n+2):nth-child(-n+3):after {
    left: 76px;
  }

  .flipdown .rotor-group:nth-child(n+2):nth-child(-n+3):before {
    bottom: 19px;
    height: 8px;
    width: 8px;
  }

  .flipdown .rotor-group:nth-child(n+2):nth-child(-n+3):after {
    bottom: 35px;
    height: 8px;
    width: 8px;
  }

  .flipdown .rotor-leaf-front,
  .flipdown .rotor-top {
    line-height: 60px;
  }

  .flipdown .rotor-leaf,
  .flipdown .rotor {
    height: 60px;
  }

  .flipdown .rotor-leaf-front,
  .flipdown .rotor-leaf-rear,
  .flipdown .rotor-top,
  .flipdown .rotor-bottom,
  .flipdown .rotor:after {
    height: 30px;
  }
}
```
